# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Incidente.create({ asunto: "Error 1", descripcion: "Ocurrieron errores", responsable: "Donatello", tipo: "Error", prioridad: 3 })
Incidente.create({ asunto: "Soporte 1", descripcion: "Se requiere soporte", responsable: "Leonardo", tipo: "Soporte", prioridad: 2 })
Incidente.create({ asunto: "Problema 1", descripcion: "Averiguar causa del problema", responsable: "Miguel Angel", tipo: "Problema", prioridad: 3 })
Incidente.create({ asunto: "Bug 1", descripcion: "La aplicación no funciona correctamente", responsable: "Rafael", tipo: "Bug", prioridad: 1 })
Incidente.create({ asunto: "Error 2", descripcion: "Ocurrieron errores", responsable: "Donatello", tipo: "Error", prioridad: 3 })
Incidente.create({ asunto: "Soporte 2", descripcion: "Se requiere soporte", responsable: "Leonardo", tipo: "Soporte", prioridad: 2 })
Incidente.create({ asunto: "Problema 2", descripcion: "Averiguar causa del problema", responsable: "Miguel Ángel", tipo: "Problema", prioridad: 3 })
Incidente.create({ asunto: "Bug 2", descripcion: "La aplicación no funciona correctamente", responsable: "Rafael", tipo: "Bug", prioridad: 1 })
Incidente.create({ asunto: "Error 3", descripcion: "Ocurrieron errores", responsable: "Donatello", tipo: "Error", prioridad: 3 })
Incidente.create({ asunto: "Soporte 3", descripcion: "Se requiere soporte", responsable: "Leonardo", tipo: "Soporte", prioridad: 2 })
Incidente.create({ asunto: "Problema 3", descripcion: "Averiguar causa del problema", responsable: "Miguel Ángel", tipo: "Problema", prioridad: 3 })
Incidente.create({ asunto: "Bug 3", descripcion: "La aplicación no funciona correctamente", responsable: "Rafael", tipo: "Bug", prioridad: 1 })
Incidente.create({ asunto: "Error 4", descripcion: "Ocurrieron errores", responsable: "Donatello", tipo: "Error", prioridad: 3 })
Incidente.create({ asunto: "Soporte 4", descripcion: "Se requiere soporte", responsable: "Leonardo", tipo: "Soporte", prioridad: 2 })
Incidente.create({ asunto: "Problema 4", descripcion: "Averiguar causa del problema", responsable: "Miguel Ángel", tipo: "Problema", prioridad: 3 })
Incidente.create({ asunto: "Bug 4", descripcion: "La aplicación no funciona correctamente", responsable: "Rafael", tipo: "Bug", prioridad: 1 })
Incidente.create({ asunto: "Error 5", descripcion: "Ocurrieron errores", responsable: "Donatello", tipo: "Error", prioridad: 3 })
Incidente.create({ asunto: "Soporte 5", descripcion: "Se requiere soporte", responsable: "Leonardo", tipo: "Soporte", prioridad: 2 })
Incidente.create({ asunto: "Problema 5", descripcion: "Averiguar causa del problema", responsable: "Miguel Ángel", tipo: "Problema", prioridad: 3 })
Incidente.create({ asunto: "Bug 5", descripcion: "La aplicación no funciona correctamente", responsable: "Rafael", tipo: "Bug", prioridad: 1 })
Incidente.create({ asunto: "Error 6", descripcion: "Ocurrieron errores", responsable: "Donatello", tipo: "Error", prioridad: 3 })
Incidente.create({ asunto: "Soporte 6", descripcion: "Se requiere soporte", responsable: "Leonardo", tipo: "Soporte", prioridad: 2 })
Incidente.create({ asunto: "Problema 6", descripcion: "Averiguar causa del problema", responsable: "Miguel Ángel", tipo: "Problema", prioridad: 3 })
Incidente.create({ asunto: "Bug 6", descripcion: "La aplicación no funciona correctamente", responsable: "Rafael", tipo: "Bug", prioridad: 1 })